### ISSUE TITLE
Where can I download these static resources?

### ISSUE THREAD

**Issue by SnowyThinker** [cas-bigdatalab/piflow-web#2]
syspara.videoName=exampleVideo.mp4
syspara.imagesPath=/data/piflowWeb/storage/image/
syspara.videosPath=/data/piflowWeb/storage/video/
syspara.xmlPath=/data/piflowWeb/storage/xml/

**Comment by sosoll7** [comment]
These static resources need to be requested from the server without downloading.
There are two ways to request:
1. Enter the pipeline configuration page to reload
![2019-09-04_105344](https://user-images.githubusercontent.com/42931639/64222772-eb3ce980-cf03-11e9-8875-081a1631299d.png)
2. Configure in the configuration file of piflow-web and automatically request to load resources after startup

**Comment by sosoll7** [comment]
@SnowyThinker 
These static resources need to be requested from the server without downloading.
There are two ways to request:
1. Enter the pipeline configuration page to reload
![2019-09-04_105344](https://user-images.githubusercontent.com/42931639/64222772-eb3ce980-cf03-11e9-8875-081a1631299d.png)
2. Configure in the configuration file of piflow-web and automatically request to load resources after startup
![2019-09-04_105938](https://user-images.githubusercontent.com/42931639/64222971-a06fa180-cf04-11e9-85f3-b6a001e57a3c.png)

**Comment by bluejoe2008** [comment]
this is a fatal bug and should be fixed as soon
providing such a tool with no components, it sounds like providing an empty OS without any software

**Comment by bluejoe2008** [comment]
this is a fatal bug and should be fixed as soon
providing such a tool with no components, it sounds like providing an empty OS without any software
