### ISSUE TITLE
CsvStringParser组件的Str参数名不对

### ISSUE THREAD

**Issue by huzk8** [cas-bigdatalab/piflow-web#5]
在piflow project中解析组件需要读取的参数名是String，而piflow web数据库中该组件模板的参数名是Str。
故在执行时会报解析错误。
![image](https://user-images.githubusercontent.com/18548053/79639932-3cfb6100-81c1-11ea-9c87-704bada289a7.png)

**Comment by judy0131** [comment]
收到，我们尽快验证，感谢反馈。


| |
xiaojie.zhu
邮箱：xiaojie.zhu@163.com
|

Signature is customized by Netease Mail Master

在2020年04月18日 22:09，huzekang 写道：

在piflow project中解析组件需要读取的参数名是String，而piflow web数据库中该组件模板的参数名是Str。
故在执行时会报解析错误。
