### ISSUE TITLE
监控页面DEBUG功能的作用

### ISSUE THREAD

**Issue by huzk8** [cas-bigdatalab/piflow-web#6]
监控页面中，使用debug模式运行后，点击线查看流经这条线的数据
![image](https://user-images.githubusercontent.com/18548053/79640639-29ea9000-81c5-11ea-8830-5c663320b0d2.png)

![image](https://user-images.githubusercontent.com/18548053/79640695-7930c080-81c5-11ea-9767-dc118c66c5c0.png)

**Comment by sosoll7** [comment]
使用debug运行时会保存每条数据的流向及内容，方便调试时校验
