### ISSUE TITLE
v0.8部署完成之后，无法登陆

### ISSUE THREAD

**Issue by baihongbin** [cas-bigdatalab/piflow-web#7]
版本：v0.8
服务器：centos7
点击前端登陆按钮没有反应，注册也是一直显示注册中。
piflow-web和piflow日志并没有相关记录。Tomcat日志也没有错误信息。
F12调试发现并没有发起请求。

**Comment by sosoll7** [comment]
Can you see if all the ports used are up？
port：6001，6002，8002，50002

**Comment by zrsaber** [comment]
I have started all the corresponding ports, but I still have this problem, what is the reason?
![image-20210716152409741](https://gitee.com/run_seven/img/raw/master/img/20210716152449.png)
ps:The version is 1.0

**Comment by zrsaber** [comment]
I solved the problem, please put the conf.js in the root under vue_webapps under tomcat that you are using：
`{
  "DEV_URL":"/piflow-web",
  "BASE_URL": "http://192.168.81.182:6002/piflow-web"
}`
Where BASE_URL is changed to the address of your server, the problem will be solved

**Comment by sosoll7** [comment]
We will optimize this problem in subsequent versions, thank you

**Comment by sosoll7** [comment]
We will optimize this problem in subsequent versions, thank you
