### ISSUE TITLE
定时调度中process的状态改变不了

### ISSUE THREAD

**Issue by Bri-Robby** [cas-bigdatalab/piflow-web#9]
V0.9版本下：启动定时调度后，flow_process中调度一次插入了2条数据，导致状态更新失败。
报错信息如下：
![image](https://user-images.githubusercontent.com/17735363/104152670-2fef6380-541b-11eb-994c-628dc8808787.png)
process列表中显示内容如下：
![image](https://user-images.githubusercontent.com/17735363/104152716-531a1300-541b-11eb-95f0-7cc8325a39e4.png)
检查yarn上执行的结果记录，如下图：
![image](https://user-images.githubusercontent.com/17735363/104152799-91afcd80-541b-11eb-910d-49ced28d7c02.png)

**Comment by sosoll7** [comment]
谢谢，我们会在后续版本中优化这个问题的

**Comment by sosoll7** [comment]
谢谢，我们会在后续版本中优化这个问题的
